### ISSUE TITLE
Compatibile with Pyodide, Error: `pure Python 3 wheel for 'datasketches'.`

### ISSUE THREAD

**Issue by bllmo** [apache/datasketches-cpp#270]
Hello, 

i am trying to import the python library in the [Pyodide](https://pyodide.org/en/stable/) with a custom build, but when i try to install i receive this error 

`running build_ext
-- The CXX compiler identification is GNU 8.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /src/tools/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/local/lib/python3.9/site-packages/cmake/data/share/cmake-3.22/Modules/GNUInstallDirs.cmake:239 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:23 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Python3: /usr/local/bin/python (found version "3.9.5") found components: Interpreter Development Development.Module Development.Embed 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /usr/local/include (found version "2.9.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /src/packages/datasketches/build/datasketches-3.2.0.1/build/temp.emscripten_wasm32-3.9
[ 20%] Building CXX object python/CMakeFiles/python.dir/src/datasketches.cpp.o
[ 20%] Building CXX object python/CMakeFiles/python.dir/src/hll_wrapper.cpp.o
[ 30%] Building CXX object python/CMakeFiles/python.dir/src/kll_wrapper.cpp.o
[ 40%] Building CXX object python/CMakeFiles/python.dir/src/cpc_wrapper.cpp.o
[ 50%] Building CXX object python/CMakeFiles/python.dir/src/fi_wrapper.cpp.o
[ 60%] Building CXX object python/CMakeFiles/python.dir/src/theta_wrapper.cpp.o
[ 70%] Building CXX object python/CMakeFiles/python.dir/src/vo_wrapper.cpp.o
[ 80%] Building CXX object python/CMakeFiles/python.dir/src/req_wrapper.cpp.o
[ 90%] Building CXX object python/CMakeFiles/python.dir/src/vector_of_kll.cpp.o
[100%] Linking CXX shared module ../../lib.emscripten_wasm32-3.9/datasketches.cpython-39-x86_64-linux-gnu.so
make[3]: *** [python/CMakeFiles/python.dir/build.make:226: ../lib.emscripten_wasm32-3.9/datasketches.cpython-39-x86_64-linux-gnu.so] Error 1
make[3]: *** Deleting file '../lib.emscripten_wasm32-3.9/datasketches.cpython-39-x86_64-linux-gnu.so'
make[2]: *** [CMakeFiles/Makefile2:657: python/CMakeFiles/python.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:664: python/CMakeFiles/python.dir/rule] Error 2
make: *** [Makefile:309: python] Error 2
Traceback (most recent call last):
  File "/src/packages/datasketches/build/datasketches-3.2.0.1/setup.py", line 82, in <module>
    setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/src/packages/datasketches/build/datasketches-3.2.0.1/setup.py", line 45, in run
    self.build_extension(ext)
  File "/src/packages/datasketches/build/datasketches-3.2.0.1/setup.py", line 78, in build_extension
    subprocess.check_call(['cmake', '--build', '.', '--target', 'python'] + build_args,
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'python', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
[2022-02-09 21:23:39] Failed building package datasketches in 47.0 seconds.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/pyodide-build/pyodide_build/__main__.py", line 62, in <module>
    main()
  File "/src/pyodide-build/pyodide_build/__main__.py", line 56, in main
    args.func(args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 821, in main
    build_package(
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 655, in build_package
    compile(
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 385, in compile
    pywasmcross.capture_compile(
  File "/src/pyodide-build/pyodide_build/pywasmcross.py", line 163, in capture_compile
    result.check_returncode()
  File "/usr/local/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/local/bin/python', 'setup.py', 'build']' returned non-zero exit status 1.`

who can help me to build an `pure python package`?

**Comment by jmalkin** [comment]
No follow-up from original poster. No plans to re-implement sketches from scratch. Closing.
